name: CI Release

on:
  push:
    branches: [ "main" ]

jobs:
  call-build-and-release:
    if: "!startsWith(github.event.head_commit.message, '[maven release plugin]')"
    uses: ./.github/workflows/build-and-release.yml
    secrets: inherit
