name: Release already tagged release

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: 'Existing git ref (tag) for this release.'
        required: true
        type: string

jobs:
  call-build-and-release:
    uses: ./.github/workflows/build-and-release.yml
    with:
      git-ref: ${{ inputs.git-ref }}
      jreleaser-do-not-tag: true
    secrets: inherit
